### ISSUE TITLE
Queue not updating [MAJOR ISSUE FOR US]

### ISSUE THREAD

**Issue by LifeGoal** [anderscripts/FiveM_Queue#3] opened 2018-09-25 16:56 UTC
Hi! Yesterday we tested this out on our server with 22 people trying to queue. The thing was that the queue never got updated. So if you started at spot 13 and 7 people before that guy got into the server. Then it never updated and it stood 13/22 instead of 6/22 for an example. They had to disconnect from the queue and connect to it again to “reload” it so it updated. We had to stop using the script just because of that. 17 in queue the last hour and there was 2 spots left on the server. So I guess they got stuck?

Anything you could look at?

**Comment by anderscripts** [comment] 2018-10-05 22:43
Solution for this problem is in testing phase.  

Can only be repo'd with 32 players active/loading state plus other players queued up.  Cannot be reproduced with less than 32 players active/loading state no matter how many are in queue.

**Comment by anderscripts** [comment] 2018-10-15 16:31
This is a confirmed bug that will be solved in release 1.1.0

**Comment by ElPumpo** [comment] 2018-10-21 18:49
Afaik there is nothing you can do about it. Deferrals in fivem are buggy, dont use them.

**Comment by anderscripts** [comment] 2018-10-29 16:06
Resolved with v 1.1.0 release

**Closed as completed by anderscripts** 2018-10-29 16:06 UTC
Labels: bug

**Comment by anderscripts** [comment] 2018-10-29 17:59
> Afaik there is nothing you can do about it. Deferrals in fivem are buggy, dont use them.

I was starting to feel this way but after rewriting v1 several times with different approaches I did find one that has been running for weeks on active servers without any freezing at all.  These issues appear to be caused by deadlocks and/or race conditions, however I did also change the approach to only use deferrals within the intial playerconnecting event, which also may have helped correct this.
